name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --all-features --verbose

  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MIRI-Compatible Toolchain
        run: |
          MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
          echo "Installing latest nightly with Miri: $MIRI_NIGHTLY"
          rustup set profile minimal
          rustup default "$MIRI_NIGHTLY"
          rustup component add miri
      - name: Run tests with MIRI
        run: cargo miri test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup rustfmt-nightly-Compatible Toolchain
        run: |
          RUSTFMT_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/rustfmt)
          echo "Installing latest nightly with rustfmt: $RUSTFMT_NIGHTLY"
          rustup set profile minimal
          rustup default "$RUSTFMT_NIGHTLY"
          rustup component add rustfmt
      - name: Run rustfmt
        run: cargo fmt -- --check
